/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversi;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class frame extends javax.swing.JFrame {
calcius c = new calcius ();
calvin k = new calvin();
fahreinheit f = new fahreinheit();
    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Pinput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pcalcius = new javax.swing.JRadioButton();
        Pfahreinheit = new javax.swing.JRadioButton();
        Pcalvin = new javax.swing.JRadioButton();
        Pcalcius1 = new javax.swing.JRadioButton();
        Pfahreinheit1 = new javax.swing.JRadioButton();
        Pcalvin1 = new javax.swing.JRadioButton();
        Phasil = new javax.swing.JButton();
        Presult = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KONVERSI SUHU");
        jLabel1.setToolTipText("");

        jLabel2.setText("INPUT ");

        jLabel3.setText("To");

        jLabel4.setText("From");

        Pcalcius.setText("CALCIUS");

        Pfahreinheit.setText("FAHREINHEIT");

        Pcalvin.setText("CALVIN");

        Pcalcius1.setText("CALCIUS");
        Pcalcius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pcalcius1ActionPerformed(evt);
            }
        });

        Pfahreinheit1.setText("FAHREINHEIT");

        Pcalvin1.setText("CALVIN");

        Phasil.setText("CALCULATE!");
        Phasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhasilActionPerformed(evt);
            }
        });

        Presult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresultActionPerformed(evt);
            }
        });

        jLabel5.setText("RESULT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pfahreinheit)
                            .addComponent(Pcalvin)
                            .addComponent(Pcalcius))
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pfahreinheit1)
                            .addComponent(Pcalvin1)
                            .addComponent(Pcalcius1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(Phasil, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Presult, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Pinput, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Pinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pcalcius)
                        .addGap(18, 18, 18)
                        .addComponent(Pfahreinheit)
                        .addGap(18, 18, 18)
                        .addComponent(Pcalvin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pcalcius1)
                        .addGap(18, 18, 18)
                        .addComponent(Pfahreinheit1)
                        .addGap(18, 18, 18)
                        .addComponent(Pcalvin1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(Phasil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Presult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pcalcius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pcalcius1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pcalcius1ActionPerformed

    private void PresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresultActionPerformed

    private void PhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhasilActionPerformed
        // TODO add your handling code here:
  
        if(Pinput.getText(). equals ("")){
            JOptionPane. showMessageDialog(null, "inputan tidak boleh kosong","eror", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
        double n = Double. parseDouble(Pinput.getText());
        
        if (Pcalvin.isSelected()){
            if (Pcalcius1.isSelected()){
                n = k.toCelcius (n);
                Presult.setText(String.valueOf(n));
                
        
            }
            if (Pcalvin1.isSelected()){
                n = k.toCalvin(n);
                Presult.setText(String.valueOf(n));
                JOptionPane.showMessageDialog(null, "tidak ada konversi yang di lakukan lagi");
            
            }
            if (Pfahreinheit1.isSelected()){
                n = k.toCelcius (n);
                Presult.setText(String.valueOf(n));
            }
                
        }
            if (Pcalcius.isSelected()){
            if (Pcalcius1.isSelected()){
                n = k.toCelcius (n);
                Presult.setText(String.valueOf(n));
                 JOptionPane.showMessageDialog(null, "tidak ada konversi yang di lakukan lagi");
                
        
            }
            if (Pcalvin1.isSelected()){
                n = k.toCalvin(n);
                Presult.setText(String.valueOf(n));
                
            
            }
            if (Pfahreinheit1.isSelected()){
                n = k.toCelcius (n);
                Presult.setText(String.valueOf(n));
            }
        
            }if (Pfahreinheit.isSelected()){
            if (Pcalcius1.isSelected()){
                n = k.toCelcius (n);
                Presult.setText(String.valueOf(n));
                 
                
        
            }
            if (Pcalvin1.isSelected()){
                n = k.toCalvin(n);
                Presult.setText(String.valueOf(n));
                
            
            }
            if (Pfahreinheit1.isSelected()){
                n = k.toCelcius (n);
                Presult.setText(String.valueOf(n));
                JOptionPane.showMessageDialog(null, "tidak ada konversi yang di lakukan lagi");
                }
            }
        }
        
    }//GEN-LAST:event_PhasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Pcalcius;
    private javax.swing.JRadioButton Pcalcius1;
    private javax.swing.JRadioButton Pcalvin;
    private javax.swing.JRadioButton Pcalvin1;
    private javax.swing.JRadioButton Pfahreinheit;
    private javax.swing.JRadioButton Pfahreinheit1;
    private javax.swing.JButton Phasil;
    private javax.swing.JTextField Pinput;
    private javax.swing.JTextField Presult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
